select nombre from producto;
select nombre, precio from producto;
select * from producto;
select nombre, precio AS "€", precio * 1.06 AS "$" from producto;
select nombre as "nom_de_'producto'", precio AS "€", precio * 1.06 AS "$" from producto;
select upper(nombre) from producto;
select lower(nombre) from producto;
select nombre, UPPER(LEFT(nombre, 2)) as primers_caracters from fabricante;
select nombre, ROUND(precio) as precio_redondeado from producto;
select nombre , truncate(precio, 0) from producto;
select codigo_fabricante from producto;
select distinct codigo_fabricante from producto;
select nombre from producto order by nombre asc;
select nombre from producto order by nombre desc;
select nombre, precio from producto order by nombre asc, precio desc;
select * from fabricante limit 5;
select * from fabricante limit 2 offset 3;
select nombre, precio from producto order by precio asc limit 1;
select nombre, precio from producto order by precio desc limit 1;
select nombre from producto where codigo_fabricante = 2;
select p.nombre, p.precio, f.nombre as "fabricante" from producto p join fabricante f;
select p.nombre, p.precio, f.nombre as "fabricante" from producto p join fabricante f order by f.nombre asc;
select p.codigo as "codigo producto", p.nombre, f.codigo as " codigo fabricante", f.nombre as "fabricante" from producto p join fabricante f;
select p.nombre as nom_del_producte, p.precio, f.nombre as "fabricante" from producto p join fabricante f on p.codigo_fabricante = f.codigo where p.precio = (select min(precio) from producto);
select p.nombre as nom_del_producte, p.precio, f.nombre as "fabricante" from producto p join fabricante f on p.codigo_fabricante = f.codigo where p.precio = (select max(precio) from producto);
select p.codigo, p.nombre, p.precio, f.nombre as "fabricante" from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = "Lenovo";
select p.codigo, p.nombre, p.precio, f.nombre as "fabricante" from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = "Crucial" and p.precio > 200;
select p.*, f.nombre as "fabricante" from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = 'Asus' or f.nombre = 'Hewlett-Packard' or f.nombre = 'Seagate';
select p.* from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre in ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre AS nom_del_producte, p.precio, f.nombre as "fabricante" FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE RIGHT(f.nombre, 1) = 'e';
SELECT p.nombre AS nom_del_producte, p.precio, f.nombre as "fabricante" FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%w%';
select p.nombre , p.precio, f.nombre as "fabricante" from producto p join fabricante f on p.codigo_fabricante = f.codigo where p.precio >= 180 order by p.precio desc, p.nombre asc;
SELECT distinct f.codigo, f.nombre AS "fabricante" FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT f.codigo, f.nombre AS nom_del_fabricant, p.nombre AS producto FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante ORDER BY f.codigo, producto;
SELECT f.codigo, f.nombre AS "fabricante" FROM fabricante f WHERE NOT EXISTS (SELECT 1 FROM producto p WHERE p.codigo_fabricante = f.codigo);
SELECT * FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo');
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo')) ORDER BY precio DESC LIMIT 1;
SELECT nombre AS "producto", precio FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo') ORDER BY precio DESC LIMIT 1;
SELECT nombre AS "producto", precio FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Hewlett-Packard') ORDER BY precio ASC LIMIT 1;
SELECT * FROM producto WHERE precio >= (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'));
SELECT p.* FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus' AND p.precio > (SELECT AVG(precio) FROM producto WHERE codigo_fabricante = f.codigo);
select apellido1, apellido2, nombre from persona where tipo = 'alumno' order by apellido1 desc;
select nombre, apellido1, apellido2, telefono from persona where telefono is null;
select nombre, apellido1, apellido2, fecha_nacimiento from persona where year(fecha_nacimiento) = 1999;
select nombre, apellido1, apellido2, telefono, nif from persona where tipo ='profesor' and telefono is null and nif like '%k';
select nombre, cuatrimestre, curso, id_grado from asignatura where cuatrimestre = 1 and curso = 3 and id_grado = 7;
select p.apellido1, p.apellido2, p.nombre, d.nombre AS nombre_del_departamento from persona p join profesor pr ON p.id = pr.id_profesor join departamento d ON pr.id_departamento = d.id where p.tipo = 'profesor' order by p.apellido1, p.apellido2, p.nombre;
select p.nombre, a.nombre, c_e.anyo_inicio, c_e.anyo_fin from persona p join curso_escolar c_e join asignatura a where p.nif = '26902806M';
select nombre from departamento where id in (select distinct pr.id_departamento from profesor pr join persona p on pr.id_profesor = p.id join asignatura a on p.id = a.id_profesor join grado g on a.id_grado = g.id where g.nombre = 'Grado en Ingeniería Informática (Plan 2015)');
select distinct p.nombre, p.apellido1, p.apellido2, nif from persona p join alumno_se_matricula_asignatura a on p.id = a.id_alumno join curso_escolar c on a.id_curso_escolar = c.id where p.tipo = 'alumno' and c.anyo_inicio = '2018/2019';
SELECT d.nombre AS nom_del_departament, p.apellido1, p.apellido2, p.nombre FROM departamento AS d RIGHT JOIN profesor AS pr ON d.id = pr.id_departamento LEFT JOIN persona AS p ON pr.id_profesor = p.id WHERE p.tipo = 'profesor' OR pr.id_departamento IS NULL ORDER BY nom_del_departament, p.apellido1, p.apellido2, p.nombre;
select p.nombre, p.apellido1, p.apellido2 from persona p left join profesor pr on p.id = pr.id_profesor where p.tipo = 'profesor' and pr.id_departamento is null;
select d.nombre from departamento d left join profesor pr on pr.id_departamento = d.id where pr.id_departamento is null;
select p.nombre, p.apellido1, p.apellido2 from persona p left join asignatura a on p.id = a.id_profesor where a.id_profesor is null;
select a.nombre from asignatura a left join profesor p on p.id_profesor = a.id_profesor where a.id_profesor is null;
SELECT d.nombre FROM departamento d LEFT JOIN profesor pr ON d.id = pr.id_departamento LEFT JOIN asignatura a ON pr.id_profesor = a.id_profesor WHERE a.id_profesor IS NULL GROUP BY d.nombre;
select COUNT(*) as "num alumnos" from persona where tipo = 'alumno';
select count(*) as "1999" from persona where tipo = 'alumno' and year(fecha_nacimiento) = 1999;
select d.nombre , COUNT(*) as Quantitat_professors from departamento d join profesor p on d.id = p.id_departamento group by d.nombre order by Quantitat_professors desc;
SELECT d.nombre AS nom_del_departament, COUNT(p.id_profesor) AS nombre_de_professors FROM departamento d LEFT JOIN profesor p ON d.id = p.id_departamento GROUP BY d.nombre;
SELECT g.nombre AS nom_del_grau, COUNT(a.id) AS nombre_d_assignatures FROM grado g LEFT JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre ORDER BY nombre_d_assignatures DESC;
SELECT g.nombre AS nom_del_grau, COUNT(a.id) AS nombre_d_assignatures FROM grado g LEFT JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre HAVING COUNT(a.id) > 40;
SELECT g.nombre as "assignatura", SUM(a.creditos) AS "credits totals" FROM grado g JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre, a.tipo;
SELECT anyo_inicio AS "Any d'inici", COUNT(DISTINCT a.id_alumno) AS "Alumnes matriculats" FROM curso_escolar ce LEFT JOIN alumno_se_matricula_asignatura a ON ce.id = a.id_curso_escolar GROUP BY anyo_inicio;
SELECT p.id, p.nombre, p.apellido1, p.apellido2, COUNT(a.id) AS nombre_d_assignatures FROM persona p LEFT JOIN asignatura a ON p.id = a.id_profesor WHERE p.tipo = 'profesor' GROUP BY p.id, p.nombre, p.apellido1, p.apellido2 ORDER BY nombre_d_assignatures DESC;
SELECT * FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento IS NOT NULL ORDER BY fecha_nacimiento ASC LIMIT 1;
SELECT p.id AS id_profesor, p.nombre, p.apellido1, p.apellido2, d.nombre AS nombre_del_departamento FROM persona p JOIN profesor pr ON p.id = pr.id_profesor LEFT JOIN asignatura a ON p.id = a.id_profesor JOIN departamento d ON pr.id_departamento = d.id WHERE pr.id_departamento IS NOT NULL AND a.id_profesor IS NULL ORDER BY id_profesor;
